linuxmint/mint-themes

files/usr/share/themes/Linux Mint/cinnamon/cinnamon.css

Uses style similar to popup-menu class instead of the old style
from alt-tab switcher (switcher-list)

Linux Mint: add window-list-preview class

---

src/Mint-X/theme/Mint-X/cinnamon/cinnamon.css

- Removed **#panel-launcher-box**: This *ID* was removed and replaced with the **panel-launchers** class ([Cinnamon commit](https://github.com/linuxmint/Cinnamon/commit/7158824c25a5ee6a586568ddeb8c4b93e8432239)).
- Removed **.panel-launcher-add-dialog-***: These classes usage were removed [around 2012](https://github.com/linuxmint/Cinnamon/commit/daa013de8ca8e4d22c04b569319dc4a47fa58392).
- Removed **.workspace-controls**, **.workspace-thumbnails-background**, **.workspace-thumbnail-indicator**, **.icon-grid** and **.overview-icon**: These classes usage were removed around 2012 ([#1](https://github.com/linuxmint/Cinnamon/commit/0bdbd02741dacb753bf576e93440d1127b8bdb45), [#2](https://github.com/linuxmint/Cinnamon/commit/379f1663025d0b9dee654a745ab0a79c75e62e19), …

[Mint-X/Cinnamon] Cleanup and fixes

---

files/usr/share/themes/Linux Mint/cinnamon/cinnamon.css

This was giving us some blurry icons in some cases

Linux Mint: Remove some unneeded icons sizes

---

src/Mint-X/theme/Mint-X/gtk-3.0/apps/mate-applications.css

Re-quest for comments: a possible fix – for issue https://github.com/mate-desktop/mate-applets/issues/317.

Mint-X (GTK-3): fix «Character Palette» applet's background

---

src/Mint-X/theme/Mint-X/gtk-3.0/apps/mate-applications.css
src/Mint-X/theme/Mint-X/gtk-3.0/gtk-widgets.css

I played around with different ways to align all the tabs with the frame correctly, but the below code was what I found to correctly align all programs.  I tried various ways but there was always a program or too that was just a little off.  This code below should correctly align all programs, unless I missed checking one.  
I restored the caja side panel coloring like it was in gtk-3.18.
I changed the checked/selected tabs in pluma and mate-terminal to theme-base-color and made the bottom border transparent, this way they correctly blend into the frame window seamlessly. 
I restored the frame border to pulseaudio volume control.
And lastly I restored the pane separator to its 3.18 look, it now has the correct icon and spacing, this looks right on every program I checked, but please …

align tabs, app specific tab coloring,  restore caja sidebar color,  improve pane separator.

---

src/Mint-X/theme/Mint-X/gtk-3.0/apps/cinnamon-applications.css
src/Mint-X/theme/Mint-X/gtk-3.0/apps/mate-applications.css

The caja tabs needed the same TLC the pluma and mate-terminal tabs did.   Tabs are now aligned to frame and checked tabs are colored correctly.

Cleanup caja tabs

---

src/Mint-X/theme/Mint-X/gtk-3.0/gtk-widgets.css

I found that the right side tab alignment was a off by a few pixels.  This was only noticeable if you had a program that had tabs that spanned across the entire windows, see screenshot.  
This was an easy fix with only a few lines of code, but @JosephMcc reminded to my to check my right to left alignment and I found that I was off there a little bit too, so I fixed that up, but noticed that the closeable page tabs were off too, see screenshot 
I went ahead and got these lined up correctly, here is a screenshot of everything.  It all looks correct but please let me know If I missed something.  
In the above screenshot you can see one last thing I did was add a border to the closable page notebook.  However there is a border that already covers the entire frame, I wanted to remove this …

more tab alignment fixes

---

files/usr/share/themes/Linux Mint/cinnamon/cinnamon.css
src/Mint-X/theme/Mint-X/cinnamon/cinnamon.css

Extra code is used to support this class, and will eventually be removed I guess.
See this line: https://github.com/linuxmint/Cinnamon/blob/c097e0d96ee9887561288b9aa4b96047eb1ee983/files/usr/share/cinnamon/applets/menu%40cinnamon.org/applet.js#L2804

Update old class name

---

files/usr/share/themes/Linux Mint/cinnamon/cinnamon.css
src/Mint-X/theme/Mint-X/cinnamon/cinnamon.css
src/Mint-Y/cinnamon/cinnamon-dark.css
src/Mint-Y/cinnamon/cinnamon.css
src/Mint-Y/cinnamon/sass/_common.scss

These changes are needed to be able to distinguish between closed, running, and focused apps on Mint-Y and Mint-X for the grouped window list applet in https://github.com/linuxmint/Cinnamon/pull/7944.

Add support for the grouped window list applet

---

files/usr/share/themes/Linux Mint/cinnamon/cinnamon.css
src/Mint-X/theme/Mint-X/cinnamon/cinnamon.css
src/Mint-Y/cinnamon/cinnamon-dark.css
src/Mint-Y/cinnamon/cinnamon.css
src/Mint-Y/cinnamon/sass/_common.scss

Also some minor improvement for the Linux Mint theme to distinguish between active hovered and focus hovered, instead of just switching to hover style. Since Mint-X uses SVGs, I wasn't sure how to do the same there.

Give the grouped window list applet unique class names

---

files/usr/share/themes/Linux Mint/cinnamon/cinnamon.css
src/Mint-X/theme/Mint-X/cinnamon/cinnamon.css
src/Mint-Y/cinnamon/sass/_common.scss

Fixes https://github.com/linuxmint/Cinnamon/issues/8111 - expo workspace entries cutting off text when fonts are scaled > 1.
After + Before Screenshots

Mint-themes fix expo workspace entry not expanding to fit scaled fonts

---

files/usr/share/themes/Mint-X/metacity-1/metacity-theme-3.xml
src/Mint-Y/metacity-1/metacity-theme-3-dark.xml
src/Mint-Y/metacity-1/metacity-theme-3.xml

Fixes ugly empty titlebar on attached dialogs when the Window Manager option `Attach dialog windows to the parent window` is enabled
Same issue affects Mint-X .... Will also make a PR for those if this is merged.
There are probably other options to fix this i.e. making attached windows use a normal_style_set as has been done with unattached dialogs and modal dialogs but this is the way most other themes do it. 
Before
After

Mint-Y & Mint-X Fix Attached Dialog Titlebar

---

src/Mint-X/theme/Mint-X/cinnamon/cinnamon.css
src/Mint-Y/cinnamon/sass/_common.scss

Fixes..
Mint-Y - keyboard applet icon size can exceed applet container at some panel settings on a vertical panel. This looks bad when highlighting the icon or in text mode.
Mint-Y - workspace-switcher simple buttons - not enough height to centre the text in the button on a vertical panel
Mint-X - workspace-switcher simple buttons - not enough height to show or centre the text in the button on a vertical panel.
Before
After

Mint X & Y - Keyboard applet & workspace-switcher simple fixes for vertical panels

---

src/Mint-Y/cinnamon/cinnamon-dark.css
src/Mint-Y/cinnamon/cinnamon.css
src/Mint-Y/cinnamon/sass/_common.scss

The only change is to zero the padding in the GWL thumbnail menu.  The other changes showing here appear to be from the last git commit, curious. Perhaps because I am doing mint-Y and X separately ?

Mint-Y: adjust for grouped-window-list-thumbnail-menu becoming active

---

src/Mint-X/theme/Mint-X/cinnamon/cinnamon.css

Mint-X - fix notification buttons on multi button notifications

---

files/usr/share/themes/Linux Mint/cinnamon/cinnamon.css
src/Mint-X/theme/Mint-X/cinnamon/cinnamon.css
src/Mint-Y/cinnamon/cinnamon-dark.css
src/Mint-Y/cinnamon/cinnamon.css

Due to https://github.com/linuxmint/cinnamon/pull/8734 it is no longer needed.
*Note: this should not be merged until the above pull request is merged

Remove about dialog styling from the cinnamon css

---

src/Mint-Y/gtk-3.0/gtk-dark.css
src/Mint-Y/gtk-3.0/gtk-darker.css
src/Mint-Y/gtk-3.0/gtk.css
src/Mint-Y/gtk-3.0/sass/_applications.scss
src/Mint-Y/gtk-3.0/sass/_common.scss

Extends using compound selectors cause issues with libsass 3.6.2 and later.
Remove these selectors to get around the issue.

Mint-Y: Update the theme for newer libsass

---

src/Mint-Y/cinnamon/sass/_common.scss

The .menu-selected-app-box style should use em's instead of px's to take account of changes to text scaling factor or default font size. This solves the problem of the description disappearing off the bottom of the menu when a larger font or font scaling is used. The value used is 2.2em so that the menu appears the same as it would if no changes to font size are made from the fresh install default (ubuntu regular, 10 and text scaling: 1.0)

Mint-Y themes: use em's instead of px's

---

src/Mint-Y/gtk-3.0/gtk-dark.css
src/Mint-Y/gtk-3.0/gtk-darker.css
src/Mint-Y/gtk-3.0/gtk.css
src/Mint-Y/gtk-3.0/sass/_libhandy.scss
src/Mint-Y/gtk-3.0/sass/gtk-dark.scss
src/Mint-Y/gtk-3.0/sass/gtk-darker.scss
src/Mint-Y/gtk-3.0/sass/gtk.scss

I copied the [_libhandy.scss](https://github.com/jnsh/arc-theme/blob/master/common/gtk-3.0/3.24/sass/_libhandy.scss) from Arc theme, and was able to fix #313 for Mint-Y after slight modification to its variable names. Then I generated the .css files with the shell script.
Mint-X does not use scss, and I could not fix it there, but at least, it is fixed in Mint-Y (and all its variants), and I did not notice any regression.
**Before** (too broad headerbar for apps with libhandy1)
**After** (notice the lean headerbar - its size is now same as other apps which use CSD but not libhandy1)
The size of the headerbar is now same as in Arc theme and also Adwaita.

Fix broad libhandy1 headerbar issue for Mint-Y (and variants)

---

src/Mint-Y/cinnamon/sass/_colors.scss

This is the fix for issue #370

Cinnamon Desktop: dark variant should get the same selected-background-color as the other GTK Controls

---

src/Mint-Y/gtk-3.0/sass/_common.scss
src/Mint-Y/gtk-4.0/sass/_common.scss

This PR addresses 2 issues:
1. In contrast to the minimize and maximize buttons, the close button does not react on mouse hover if the window is not focused. This is confusing: the user may think the close button is disabled. The change brings back the behavior from LM 20.3, where the close button changed its background color on hover even if the window is not focused.
3. The contrast of the minimize and maximize icon and the background on mouse hover on unfocused windows is poor. The change brings back the behavior from LM 20.3, where the minimize and maximize icon changed its color (to $selected_fg_color) on mouse hover if the window is not focused.

Fix for title bar buttons on unfocused windows

---

src/Mint-Y/cinnamon/cinnamon-dark.css
src/Mint-Y/cinnamon/cinnamon.css
src/Mint-Y/cinnamon/sass/_common.scss

to allow for different default font sizes and text scaling. fixes https://github.com/linuxmint/cinnamon-spices-applets/issues/4781
fixes: https://github.com/linuxmint/cinnamon/issues/11572
I've set the ems value so that the applet looks the same as before with the default ubuntu regular 10 font in mint 21.1.

Mint-Y Cinnamon theme - sound applet - use ems instead of px for overlay.

---

files/usr/share/themes/Linux Mint/cinnamon/cinnamon.css
src/Mint-X/theme/Mint-X/cinnamon/cinnamon.css

..to allow for different default font sizes and text scaling.
I've set the ems value so that the applet looks the same as before with the default ubuntu regular 10 font in mint 21.1.
\+ Ditto for cinnamon theme Linux Mint.

Mint-X cinnamon theme - sound applet. Use ems instead of px for overlay height.

---

src/Mint-Y/cinnamon/cinnamon-dark.css
src/Mint-Y/cinnamon/cinnamon.css
src/Mint-Y/cinnamon/sass/_common.scss

Add initial support for .menu-category-button:hover (https://github.com/linuxmint/cinnamon/pull/11473)

Mint-Y cinnamon - Add support for .menu-category-button:hover

---

src/Mint-Y/gtk-2.0/main.rc

The current Mint themes in 21 and 21.1 have a major issue: selected text is not visible as soon as the window loses the focus:
This fix brings back the behavior of Mint 20.3 where the text selection is visible even if the window is not focused.
The additional `image { ... }` is necessary to keep the white background, otherwise it will look like this:
fixes #438

Fix text selection on unfocused windows

---

src/Mint-Y/gtk-3.0/sass/_common.scss
src/Mint-Y/gtk-4.0/sass/_common.scss

I'd like to suggest to unify the vertical and horizontal window title bar padding. The different distances from the close button to the top and right border, introduced with Mint 21, doesn't look correct to me even after months working with it.
Other desktop environments also do it like this and I think it looks more pleasant and accurate.
This change brings back the look from Mint 20.3, which was already perfect from my point of view.

Adjust Title Bar Padding

---

files/usr/share/themes/Linux Mint/cinnamon/cinnamon.css

Similar to linuxmint/cinnamon#11755

Linux Mint/cinnamon.css: Center text in .applet-box

---

files/usr/share/themes/Linux Mint/cinnamon/cinnamon.css
src/Mint-X/theme/Mint-X/cinnamon/cinnamon.css
src/Mint-Y/cinnamon/cinnamon-dark.css
src/Mint-Y/cinnamon/cinnamon.css
src/Mint-Y/cinnamon/sass/_common.scss

This is in tandem with linuxmint/cinnamon#11756
Discussion: linuxmint/discussions#79

Remove height from sound-player-overlay so that text can wrap cleanly

---

src/Mint-X/theme/Mint-X/cinnamon/cinnamon.css
src/Mint-Y/cinnamon/cinnamon-dark.css
src/Mint-Y/cinnamon/cinnamon.css
src/Mint-Y/cinnamon/sass/_common.scss

This updates support in both Mint-X and Mint-Y themes.

Cinnamon: Add support for the new polkit dialog

---

files/usr/share/themes/Linux Mint/cinnamon/cinnamon.css

Remove fixed width of label since "text-align: center;" doesn't do anything and text is left aligned.
cf. https://github.com/linuxmint/cinnamon/pull/12171

Linux Mint theme fix expo-workspaces-name-entry

---

src/Mint-X/theme/Mint-X/gtk-3.0/gtk-dark.css
src/Mint-X/theme/Mint-X/gtk-3.0/gtk.css
src/Mint-X/theme/Mint-X/gtk-3.0/sass/_colors-public.scss
src/Mint-Y/gtk-3.0/gtk-dark.css
src/Mint-Y/gtk-3.0/gtk.css
src/Mint-Y/gtk-3.0/sass/_colors-public.scss
src/Mint-Y/gtk-3.0/sass/_colors.scss
src/Mint-Y/gtk-4.0/gtk-dark.css
src/Mint-Y/gtk-4.0/gtk.css
src/Mint-Y/gtk-4.0/sass/_colors-public.scss
src/Mint-Y/gtk-4.0/sass/_colors.scss

This is used by XDG-DESKTOP-PORTAL-XAPP to provide the accent color via the accent color API.
It results in coloring libAdwaita apps with the selected GTK3 theme's accent color*
* Well, kinda, because libAdwaita stays in its own palette and choose its own version of red, or blue, or whatever is closest to our theme's accent.
ref: https://github.com/linuxmint/xdg-desktop-portal-xapp/pull/23

Define accent-color

---

src/Mint-X/theme/Mint-X/cinnamon/cinnamon.css

Add support for cinnamon 6.4. Some things could probably use some tweaking: spacing, padding etc. but it all looks reasonable enough for now. ~~I haven't implemented the dialog button destructive_action pseudo class (which I guess is optional anyway)~~ and some old class names and perhaps unnecessary duplication could be removed. ~~I couldn't test the Audio device selection dialog or network Auth dialog but they should look the same as the other dialogs.~~
Edit: Audio device selection dialog support added and tested. NetworkSecretDialog tested and ok.
Edit: Added dialog-button:destructive-action as red text. Changing button background color would mean creating a new set of button assets and the red button text looks ok anyway.

Mint-X: Add support for cinnamon 6.4
